version: "3.9"
services:
  movie:
    build: ./movie/
    ports:
      - "3001:3001"
  showtime:
    build: ./showtime/
    ports:
      - "3002:3002"
  booking:
    build: ./booking/
    ports:
        - "3003:3003"
  booking-grpc:
    build: ./booking-grpc/
    ports:
        - "3005:3005"
  user:
    build: ./user/
    ports:
        - "3004:3004"
  user2:
    build: ./user2/
    ports:
        - "3006:3006"

