# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\t\"B\n\x11NewBookingForUser\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0f\n\x07movieid\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\"}\n\x0b\x42ookingData\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12,\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x1d.BookingData.InnerBookingData\x1a\x30\n\x10InnerBookingData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x0e\n\x0c\x45mptyBooking2\x9b\x01\n\x07\x42ooking\x12*\n\x07GetJson\x12\r.EmptyBooking\x1a\x0c.BookingData\"\x00\x30\x01\x12,\n\x11GetBookingForUser\x12\x07.UserId\x1a\x0c.BookingData\"\x00\x12\x36\n\x10\x41\x64\x64\x42ookingByUser\x12\x12.NewBookingForUser\x1a\x0c.BookingData\"\x00\x62\x06proto3')



_USERID = DESCRIPTOR.message_types_by_name['UserId']
_NEWBOOKINGFORUSER = DESCRIPTOR.message_types_by_name['NewBookingForUser']
_BOOKINGDATA = DESCRIPTOR.message_types_by_name['BookingData']
_BOOKINGDATA_INNERBOOKINGDATA = _BOOKINGDATA.nested_types_by_name['InnerBookingData']
_EMPTYBOOKING = DESCRIPTOR.message_types_by_name['EmptyBooking']
UserId = _reflection.GeneratedProtocolMessageType('UserId', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:UserId)
  })
_sym_db.RegisterMessage(UserId)

NewBookingForUser = _reflection.GeneratedProtocolMessageType('NewBookingForUser', (_message.Message,), {
  'DESCRIPTOR' : _NEWBOOKINGFORUSER,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:NewBookingForUser)
  })
_sym_db.RegisterMessage(NewBookingForUser)

BookingData = _reflection.GeneratedProtocolMessageType('BookingData', (_message.Message,), {

  'InnerBookingData' : _reflection.GeneratedProtocolMessageType('InnerBookingData', (_message.Message,), {
    'DESCRIPTOR' : _BOOKINGDATA_INNERBOOKINGDATA,
    '__module__' : 'booking_pb2'
    # @@protoc_insertion_point(class_scope:BookingData.InnerBookingData)
    })
  ,
  'DESCRIPTOR' : _BOOKINGDATA,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingData)
  })
_sym_db.RegisterMessage(BookingData)
_sym_db.RegisterMessage(BookingData.InnerBookingData)

EmptyBooking = _reflection.GeneratedProtocolMessageType('EmptyBooking', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYBOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:EmptyBooking)
  })
_sym_db.RegisterMessage(EmptyBooking)

_BOOKING = DESCRIPTOR.services_by_name['Booking']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERID._serialized_start=17
  _USERID._serialized_end=37
  _NEWBOOKINGFORUSER._serialized_start=39
  _NEWBOOKINGFORUSER._serialized_end=105
  _BOOKINGDATA._serialized_start=107
  _BOOKINGDATA._serialized_end=232
  _BOOKINGDATA_INNERBOOKINGDATA._serialized_start=184
  _BOOKINGDATA_INNERBOOKINGDATA._serialized_end=232
  _EMPTYBOOKING._serialized_start=234
  _EMPTYBOOKING._serialized_end=248
  _BOOKING._serialized_start=251
  _BOOKING._serialized_end=406
# @@protoc_insertion_point(module_scope)
